service: gruby-front
runtime: nodejs10
handlers:
  - url: /
    static_files: public/index.html
    upload: public/index.html
  - url: /report
    static_files: public/index.html
    upload: public/index.html
  - url: /
    static_dir: public